name: Frontend CI (Debug + Docker)

on:
  push:
    branches: [ main ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (FIXED VERSION)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      #5 login to docker hub
      - name: docker login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      #6 build docker image
      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/clean-blog-app:latest .

      #7 push docker image
      - name: push docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/clean-blog-app:latest



      #setup kubectl 
      - name: setup kubectl
        uses: azure/setup-kubectl@v4

      # configure kubeconfig
      - name: set kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      #10. deploy to kubernetes
      - name: deploy k8s
        run: |
          kebectl set image deployment/frontend-deployement \
          frontend-container=jaydipaws/clean-blog-app:latest
    
          kubectl rollout status deployment/frontend-deployment


